### ISSUE TITLE
Able to save same contact multiple times.

### ISSUE THREAD

**Issue by Vishesh-Pandey** [Vishesh-Pandey/rapid-whatsapp#1]
So if I save a contact already with a name like ABC, then the program should not allow me to save the contact with the same name.

![Screenshot 2023-05-03 203025](https://user-images.githubusercontent.com/74998585/235956411-8a6f2ca0-705e-4672-8a7b-7443e6861ffc.png)

**Comment by ThienBNguyen** [comment]
Hi Vishesh-Pandey, I am interested in the issue. can I try to solve it?
