### ISSUE TITLE
Moving contacts to a separate component 

### ISSUE THREAD

**Issue by MZHoffman** [Vishesh-Pandey/rapid-whatsapp#24]
that will save us about 80 lines of code in App.js
Happy to do it

**Comment by Vishesh-Pandey** [comment]
Great Idea. I was planning to split App.js into three different components. We can start by creating a separate component for contacts.

**Comment by MZHoffman** [comment]
> Great Idea. I was planning to split App.js into three different components. We can start by creating a separate component for contacts.

Done

**Comment by MZHoffman** [comment]
This can be closed now
