### ISSUE TITLE
Adding "no" option to swal confirmation

### ISSUE THREAD

**Issue by MZHoffman** [Vishesh-Pandey/rapid-whatsapp#27]
Not everyone will know you just need to click outside to abort deletion.

Kinda already done it on my end. let me know if I should submit PR

![image](https://github.com/Vishesh-Pandey/rapid-whatsapp/assets/25756053/46b54185-35b9-499d-b943-223d304c17aa)

**Comment by Vishesh-Pandey** [comment]
Yes, please. Even I was about to do that. Thank you!
