### ISSUE TITLE
Feature: Displaying contact name in the history if not in contacts adding "save contact" button

### ISSUE THREAD

**Issue by MZHoffman** [Vishesh-Pandey/rapid-whatsapp#30]
Feature: Displaying contact name in the history. if not in contacts adding "save contact" button

**Comment by MZHoffman** [comment]
I can work on it as well.

I imagine the best would be to move history and contact to the same array to store objects like below

`{ name: null, number: "1234567890", history: ["timestap", "timestamp2", 'timestamp3'] }`

then we need a function that places add button if name is null and we han nicely print whole of history under one entry of the  history do we dont have duplicates. 
something like
![image](https://github.com/Vishesh-Pandey/rapid-whatsapp/assets/25756053/3bbf599e-1a05-430d-9524-bdc2e52c7f7c)

**Comment by Tushar12222** [comment]
Hey @MZHoffman ,
Your suggestion is great . I too would like to give a suggestion here: we could use a set for the history part so that in the future we can implement a filter option if necessary. What do you think?
