### ISSUE TITLE
delete individual history

### ISSUE THREAD

**Issue by Vishesh-Pandey** [Vishesh-Pandey/rapid-whatsapp#36]
There should be an option to delete a specific history.

**Comment by Shubh8899** [comment]
I would like to work on this issue.

**Comment by Shubh8899** [comment]
@Vishesh-Pandey  I am not able to reproduce History(Chat history is not available to me). Maybe i am missing something, can you help me with steps to display history?

**Comment by Vishesh-Pandey** [comment]
Okay, so to produce history you need to put a number in the input tag and then click on chat on WhatsApp. The moment you click on chat it will produce history and will get saved in your local storage.

**Comment by Shubh8899** [comment]
Okay, so i encountered an error while reproducing the steps you mentioned. I want to confirm if you are also facing the same issue? If it is detected/ is anybody working on it?

[Console & error](https://drive.google.com/file/d/19qKPYrb0h_P4JAiU8HE2Qp64N_vJqjj3/view?usp=share_link)

[Local Storage](https://drive.google.com/file/d/1KSgnADPDWYwtaT5hVuKFjw6_bYs8sUJ8/view?usp=share_link)

**Comment by Shubh8899** [comment]
Please find screenshot of error in below links.
[Error](https://drive.google.com/file/d/19qKPYrb0h_P4JAiU8HE2Qp64N_vJqjj3/view?usp=share_link)

**Comment by Vishesh-Pandey** [comment]
Okay... I fixed the error. Please Sync fork -> Update branch and try again. Let me know if you are still getting this error.
