### ISSUE TITLE
Display contact name in history if contact with that number is already saved

### ISSUE THREAD

**Issue by Vishesh-Pandey** [Vishesh-Pandey/rapid-whatsapp#45]
History only displays the contact number. It would be a great idea if we can display the contact name if that number is already saved in contacts.

**Comment by SD191100** [comment]
@Vishesh-Pandey 
can I work on this project 
I am learning web development backend 
and want to learn new things and start contributions

**Comment by Vishesh-Pandey** [comment]
@SD191100 are you working on it?
