### ISSUE TITLE
Combine error statement into single useState

### ISSUE THREAD

**Issue by Vishesh-Pandey** [Vishesh-Pandey/rapid-whatsapp#5]
So there are two error statements
1 - Number already exist and
2 - Name already exist

We can handle both of these errors using a single useState.
So showing one of the errors at a time will be enough.

Multiple errors getting displayed even when the name is unique.
![image](https://user-images.githubusercontent.com/74998585/236244248-9c934475-1d9f-44db-af56-821ebd1e4ec8.png)

**Comment by MZHoffman** [comment]
Hi,

Pull request submitted.
This is my first pull request

Thank you

**Comment by MZHoffman** [comment]
Great,

How about i fix the typo by the way moving from multiple useState's to one neat useReducer?
